name = "MomentumED"
uuid = "2c2e6bdd-50a7-494a-93d8-6f138df00727"
authors = ["Alice loves Bob <zou.bo.phys@gmail.com>"]
version = "1.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Combinatorics = "1.0.3"
KrylovKit = "0.10.0"
julia = "1.11"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f0-a6b5-11e9-1cdc-6bdb1d677c35"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test", "BenchmarkTools"]
