name = "MomentumED"
uuid = "2c2e6bdd-50a7-494a-93d8-6f138df00727"
version = "0.1.4"
authors = ["Alice loves Bob <zou.bo.phys@gmail.com>"]

[deps]
EDCore = "67ba95b5-0c7c-4a9c-9737-2f4756a96b17"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
EDCore = "0.1.4"
KrylovKit = "0.10.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
